apiVersion: v1
kind: Secret
metadata:
  name: auth-service-secret
  namespace: fiap-tc-f2
type: Opaque
stringData:
  DATABASE_URL: "postgres://postgres:postgres123@postgres-svc:5432/postgres?sslmode=disable"
  MASTER_KEY: "admin-secreto-123"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: auth-service-config-map
  namespace: fiap-tc-f2
data:
  PORT: "8001"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  namespace: fiap-tc-f2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
        - name: auth-service
          image: auth-service:local
          imagePullPolicy: Never
          ports:
            - containerPort: 8001
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 200m
              memory: 256Mi
          livenessProbe:
            httpGet:
              path: /health
              port: 8001
            initialDelaySeconds: 15
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /health
              port: 8001
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 3
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: auth-service-secret
                  key: DATABASE_URL
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: auth-service-config-map
                  key: PORT
            - name: MASTER_KEY
              valueFrom:
                secretKeyRef:
                  name: auth-service-secret
                  key: MASTER_KEY
---
apiVersion: v1
kind: Service
metadata:
  name: auth-service-svc
  namespace: fiap-tc-f2
spec:
  selector:
    app: auth-service
  ports:
    - port: 8001
      targetPort: 8001
